"""empty message

Revision ID: dc40bcc07212
Revises: 2fcdfc37bd80
Create Date: 2019-10-10 00:19:24.901187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc40bcc07212'
down_revision = '2fcdfc37bd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark_users',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('bookmark_user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bookmark_user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    op.create_table('bookmark_posts',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('bookmark_post_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bookmark_post_id'], ['blog_posts.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('bookmarks_user')
    op.drop_table('bookmarks_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks_post',
                    sa.Column('created_at', sa.DATETIME(), nullable=True),
                    sa.Column('modified_at', sa.DATETIME(), nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('bookmark_post_id', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['bookmark_post_id'], ['blog_posts.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bookmarks_user',
                    sa.Column('created_at', sa.DATETIME(), nullable=True),
                    sa.Column('modified_at', sa.DATETIME(), nullable=True),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('bookmark_user_id', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['bookmark_user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('bookmark_posts')
    op.drop_table('bookmark_users')
    # ### end Alembic commands ###
